# Generated by Django 4.2.5 on 2023-11-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
