# Generated by Django 4.2.5 on 2023-11-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sectional_record',
            field=models.TextField(),
        ),
    ]
