# Generated by Django 4.2.5 on 2023-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_rename_sectional_record_history_sectional_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('num_players', models.IntegerField()),
                ('first_place_user_id', models.IntegerField(blank=True, null=True)),
                ('first_place_user_distance', models.FloatField(blank=True, null=True)),
                ('second_place_user_id', models.IntegerField(blank=True, null=True)),
                ('second_place_user_distance', models.FloatField(blank=True, null=True)),
                ('third_place_user_id', models.IntegerField(blank=True, null=True)),
                ('third_place_user_distance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='group_history_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
