# Generated by Django 4.2.5 on 2023-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_group_history_history_group_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='group_history_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
