# Generated by Django 4.2.5 on 2023-11-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_history_group_history_id_alter_history_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_mission_succeeded',
            field=models.IntegerField(default=0),
        ),
    ]
