# Generated by Django 4.2.5 on 2023-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_age_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/temp_profile.jpeg', max_length=500, upload_to='profile_images'),
        ),
    ]
