# Generated by Django 4.2.5 on 2023-11-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_exp"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="profile_image",),
    ]
