# Generated by Django 4.2.5 on 2023-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="badge_collection",
            field=models.IntegerField(default=1000000000),
        ),
    ]
