# Generated by Django 4.2.5 on 2023-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_customuser_badge_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/temp_profile.jpeg",
                max_length=500,
                upload_to="profile_images",
            ),
        ),
    ]
